# List of wireless cards returned by the stats module
stats_wireless_cards = [
    {
        'name': 'phy0',
        'vht-capabilities': True,
        'channels': [{'disabled': False, 'radar': False, 'frequency': 2412,
                      'number': 1},
                     {'disabled': False, 'radar': False, 'frequency': 2417,
                      'number': 2},
                     {'disabled': False, 'radar': False, 'frequency': 2422,
                      'number': 3},
                     {'disabled': False, 'radar': False, 'frequency': 2427,
                      'number': 4},
                     {'disabled': False, 'radar': False, 'frequency': 2432,
                      'number': 5},
                     {'disabled': False, 'radar': False, 'frequency': 2437,
                      'number': 6},
                     {'disabled': False, 'radar': False, 'frequency': 2442,
                      'number': 7},
                     {'disabled': False, 'radar': False, 'frequency': 2447,
                      'number': 8},
                     {'disabled': False, 'radar': False, 'frequency': 2452,
                      'number': 9},
                     {'disabled': False, 'radar': False, 'frequency': 2457,
                      'number': 10},
                     {'disabled': False, 'radar': False, 'frequency': 2462,
                      'number': 11},
                     {'disabled': False, 'radar': False, 'frequency': 2467,
                      'number': 12},
                     {'disabled': False, 'radar': False, 'frequency': 2472,
                      'number': 13},
                     {'disabled': True, 'radar': False, 'frequency': 2484,
                      'number': 14},
                     {'disabled': False, 'radar': False, 'frequency': 5180,
                      'number': 36},
                     {'disabled': False, 'radar': False, 'frequency': 5200,
                      'number': 40},
                     {'disabled': False, 'radar': False, 'frequency': 5220,
                      'number': 44},
                     {'disabled': False, 'radar': False, 'frequency': 5240,
                      'number': 48},
                     {'disabled': False, 'radar': True, 'frequency': 5260,
                      'number': 52},
                     {'disabled': False, 'radar': True, 'frequency': 5280,
                      'number': 56},
                     {'disabled': False, 'radar': True, 'frequency': 5300,
                      'number': 60},
                     {'disabled': False, 'radar': True, 'frequency': 5320,
                      'number': 64},
                     {'disabled': False, 'radar': True, 'frequency': 5500,
                      'number': 100},
                     {'disabled': False, 'radar': True, 'frequency': 5520,
                      'number': 104},
                     {'disabled': False, 'radar': True, 'frequency': 5540,
                      'number': 108},
                     {'disabled': False, 'radar': True, 'frequency': 5560,
                      'number': 112},
                     {'disabled': False, 'radar': True, 'frequency': 5580,
                      'number': 116},
                     {'disabled': False, 'radar': True, 'frequency': 5600,
                      'number': 120},
                     {'disabled': False, 'radar': True, 'frequency': 5620,
                      'number': 124},
                     {'disabled': False, 'radar': True, 'frequency': 5640,
                      'number': 128},
                     {'disabled': False, 'radar': True, 'frequency': 5660,
                      'number': 132},
                     {'disabled': False, 'radar': True, 'frequency': 5680,
                      'number': 136},
                     {'disabled': False, 'radar': True, 'frequency': 5700,
                      'number': 140},
                     {'disabled': True, 'radar': False, 'frequency': 5745,
                      'number': 149},
                     {'disabled': True, 'radar': False, 'frequency': 5765,
                      'number': 153},
                     {'disabled': True, 'radar': False, 'frequency': 5785,
                      'number': 157},
                     {'disabled': True, 'radar': False, 'frequency': 5805,
                      'number': 161},
                     {'disabled': True, 'radar': False, 'frequency': 5825,
                      'number': 165}]
    },
    {
        'name': 'phy1',
        'vht-capabilities': False,
        'channels': [{'disabled': False, 'radar': False, 'frequency': 2412, 'number': 1},
                     {'disabled': False, 'radar': False, 'frequency': 2417, 'number': 2},
                     {'disabled': False, 'radar': False, 'frequency': 2422, 'number': 3},
                     {'disabled': False, 'radar': False, 'frequency': 2427, 'number': 4},
                     {'disabled': False, 'radar': False, 'frequency': 2432, 'number': 5},
                     {'disabled': False, 'radar': False, 'frequency': 2437, 'number': 6},
                     {'disabled': False, 'radar': False, 'frequency': 2442, 'number': 7},
                     {'disabled': False, 'radar': False, 'frequency': 2447, 'number': 8},
                     {'disabled': False, 'radar': False, 'frequency': 2452, 'number': 9},
                     {'disabled': False, 'radar': False, 'frequency': 2457, 'number': 10},
                     {'disabled': False, 'radar': False, 'frequency': 2462, 'number': 11},
                     {'disabled': False, 'radar': False, 'frequency': 2467, 'number': 12},
                     {'disabled': False, 'radar': False, 'frequency': 2472, 'number': 13},
                     {'disabled': True, 'radar': False, 'frequency': 2484, 'number': 14}]
    },
]
